### ISSUE TITLE
version control tool to clone all image-render-* repos at once

### ISSUE THREAD

**Issue by bhomaidan1990** [boschresearch/image-render-setup#5]
> Note: this is an enhancement request, and not a bug report, please feel free to close it whenever you want.

It will be easier to clone the `Catharsys` repositories using a [version control system (vcs tool)](https://github.com/dirk-thomas/vcstool) by adding all the required repos to a yaml file:
```yml
repositories:
  setup:
   type: git
   url: https://github.com/boschresearch/image-render-setup.git
   version: stable
  gui:
   type: git
   url: https://github.com/boschresearch/image-render-gui
   version: stable
  automation:
   type: git
   url: https://github.com/boschresearch/image-render-automation
   version: stable
  generative:
   type: git
   url: https://github.com/boschresearch/image-render-generative
   version: stable
```
and after that using vcs to import all at once:
```sh
$ vcs import . --input https://github.com/boschresearch/image-render-setup/main/pkgs.yml
```
thanks in advance.
